# Generated by Django 2.0.2 on 2019-05-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppProCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns_appname', models.CharField(max_length=100, verbose_name='网安平台企业名称')),
                ('ns_code', models.CharField(max_length=10, verbose_name='网安平台企业code')),
                ('vi_ec_id', models.CharField(blank=True, max_length=20, verbose_name='智云企业id')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(blank=True, default='auto create', help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '网安-平台企业名称',
                'verbose_name_plural': '网安-平台企业名称',
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessType', models.CharField(max_length=30, verbose_name='业务类型')),
                ('en', models.CharField(max_length=15, verbose_name='EN')),
                ('code', models.CharField(max_length=2, verbose_name='CODE')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(blank=True, default='auto create', help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': 'audit3.0-业务类型',
                'verbose_name_plural': 'audit3.0-业务类型',
            },
        ),
        migrations.CreateModel(
            name='DpiConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('vi_type_id', models.CharField(max_length=50, verbose_name='虚拟身份类型id')),
                ('rule_data', models.CharField(max_length=200, verbose_name='规则内容')),
                ('rule_begin_match', models.CharField(max_length=50, verbose_name='规则匹配开始内容')),
                ('rule_end_match', models.CharField(max_length=50, verbose_name='规则匹配结束内容')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(blank=True, default='auto create', help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': 'dpiConf-配置详情',
                'verbose_name_plural': 'dpiConf-配置详情',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseCoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='企业名称')),
                ('en', models.CharField(blank=True, max_length=15, verbose_name='EN')),
                ('code', models.CharField(max_length=4, verbose_name='CODE')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(blank=True, default='auto create', help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('typeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.BusinessType', verbose_name='业务类型')),
            ],
            options={
                'verbose_name': 'audit3.0-企业名称',
                'verbose_name_plural': 'audit3.0-企业名称',
            },
        ),
        migrations.CreateModel(
            name='IdentityTypeCoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identityType', models.CharField(max_length=30, verbose_name='身份类型编码')),
                ('en', models.CharField(max_length=15, verbose_name='EN')),
                ('code', models.CharField(max_length=1, verbose_name='CODE')),
                ('explaines', models.CharField(max_length=60, verbose_name='说明')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(blank=True, default='auto create', help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': 'audit3.0-身份类型编码',
                'verbose_name_plural': 'audit3.0-身份类型编码',
            },
        ),
        migrations.CreateModel(
            name='Multimode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=20, verbose_name='多模类型id')),
                ('type_value', models.CharField(max_length=50, verbose_name='多模类型值')),
            ],
            options={
                'verbose_name': 'dpiConf-多模',
                'verbose_name_plural': 'dpiConf-多模',
            },
        ),
        migrations.CreateModel(
            name='NetSafetyPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=100, verbose_name='网安平台名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='网安平台编码')),
                ('status', models.CharField(default=0, max_length=1, verbose_name='状态-0可用-1不可用')),
            ],
            options={
                'verbose_name': '网安-平台基础信息',
                'verbose_name_plural': '网安-平台基础信息',
            },
        ),
        migrations.CreateModel(
            name='ProtocolApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=100, verbose_name='应用名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='应用编码')),
                ('status', models.CharField(default=0, max_length=1, verbose_name='状态-0可用-1不可用')),
                ('platformCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.NetSafetyPlatform', verbose_name='平台编码')),
            ],
            options={
                'verbose_name': '网安-平台应用信息',
                'verbose_name_plural': '网安-平台应用信息',
            },
        ),
        migrations.CreateModel(
            name='ProtocolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=100, verbose_name='类型名称')),
                ('code', models.CharField(max_length=100, verbose_name='类型编码')),
                ('status', models.CharField(default=0, max_length=1, verbose_name='状态-0可用-1不可用')),
                ('platformCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.NetSafetyPlatform', verbose_name='平台编码')),
            ],
            options={
                'verbose_name': '网安-平台类型信息',
                'verbose_name_plural': '网安-平台类型信息',
            },
        ),
        migrations.AddField(
            model_name='protocolapplication',
            name='typeCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpi.ProtocolType', verbose_name='类型编码'),
        ),
        migrations.AddField(
            model_name='dpiconf',
            name='multimode_id',
            field=models.ForeignKey(help_text='多模id', on_delete=django.db.models.deletion.CASCADE, to='dpi.Multimode', verbose_name='多模id'),
        ),
        migrations.AddField(
            model_name='appprocode',
            name='platformCode',
            field=models.ForeignKey(help_text='网安平台编码', on_delete=django.db.models.deletion.CASCADE, to='dpi.NetSafetyPlatform', verbose_name='网安平台编码'),
        ),
    ]
