# Generated by Django 2.0.2 on 2019-05-23 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpiconf',
            old_name='multimode_id',
            new_name='multimode',
        ),
        migrations.AddField(
            model_name='dpiconf',
            name='status',
            field=models.CharField(default=1, max_length=1, verbose_name='状态:1可用0不可用'),
        ),
        migrations.AddField(
            model_name='multimode',
            name='comment',
            field=models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='multimode',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multimode',
            name='status',
            field=models.CharField(default=1, max_length=1, verbose_name='状态:1可用0不可用'),
        ),
        migrations.AddField(
            model_name='multimode',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AddField(
            model_name='multimode',
            name='user',
            field=models.CharField(blank=True, default='auto create', help_text='操作人', max_length=30, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='dpiconf',
            name='vi_type_id',
            field=models.IntegerField(verbose_name='虚拟身份类型id'),
        ),
        migrations.AlterField(
            model_name='multimode',
            name='type_id',
            field=models.IntegerField(verbose_name='多模类型id'),
        ),
    ]
