# Generated by Django 2.0.2 on 2019-05-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0002_auto_20190523_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpiPcap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_type_id', models.IntegerField(verbose_name='虚拟身份类型id')),
                ('taget_account', models.CharField(max_length=100, verbose_name='检索账号')),
                ('phone_model', models.CharField(max_length=50, verbose_name='手机型号')),
                ('os_version', models.CharField(max_length=50, verbose_name='操作系统版本')),
                ('app_type', models.CharField(max_length=50, verbose_name='应用类型:app/web')),
                ('app_version', models.CharField(max_length=50, verbose_name='应用版本')),
                ('md5', models.CharField(max_length=50, verbose_name='pacp文件的md5')),
                ('file_save_path_name', models.CharField(max_length=200, verbose_name='文件存储的绝对路径')),
                ('status', models.CharField(default=1, max_length=1, verbose_name='状态:1可用0不可用')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(blank=True, default='auto create', help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': 'dpiConf-Pcap文件维护',
                'verbose_name_plural': 'dpiConf-Pcap文件维护',
            },
        ),
        migrations.AddField(
            model_name='dpiconf',
            name='dpipcap',
            field=models.ForeignKey(default=0, help_text='命中pcapID', on_delete=django.db.models.deletion.CASCADE, to='dpi.DpiPcap', verbose_name='命中pcapID'),
            preserve_default=False,
        ),
    ]
