# Generated by Django 2.0.2 on 2019-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_auto_20190525_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpiconf',
            name='dpipcap',
        ),
        migrations.AddField(
            model_name='dpiconf',
            name='dpipcap_id',
            field=models.IntegerField(default=1, verbose_name='dpipcapID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dpipcap',
            name='app_type',
            field=models.CharField(max_length=20, verbose_name='应用类型:app/web'),
        ),
        migrations.AlterField(
            model_name='dpipcap',
            name='os_version',
            field=models.CharField(max_length=100, verbose_name='操作系统版本'),
        ),
        migrations.AlterField(
            model_name='dpipcap',
            name='phone_model',
            field=models.CharField(max_length=100, verbose_name='手机型号'),
        ),
    ]
