# Generated by Django 2.0.2 on 2019-06-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_M_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('面板AP', '面板AP'), ('二合一', '二合一'), ('三合一', '三合一'), ('四合一', '四合一'), ('吸顶AP', '吸顶AP'), ('AC网关', 'AC网关'), ('光猫AP', '光猫AP'), ('嗅探光猫', '嗅探光猫'), ('嗅探2合1', '嗅探2合1'), ('室外AP', '室外AP'), ('机顶盒', '机顶盒'), ('交换机', '交换机')], help_text='类型', max_length=50, verbose_name='类型')),
                ('oem_id', models.CharField(blank=True, help_text='设备厂商id', max_length=50, verbose_name='设备厂商id')),
                ('zy_model', models.CharField(blank=True, help_text='中建智云型号', max_length=100, unique=True, verbose_name='中建智云型号')),
                ('oem_model', models.CharField(blank=True, help_text='厂商型号', max_length=100, verbose_name='厂商型号')),
                ('old_model', models.CharField(blank=True, help_text='老型号', max_length=100, verbose_name='老型号')),
                ('oem_name', models.CharField(blank=True, default='', help_text='厂商名称', max_length=100, null=True, verbose_name='厂商名称')),
                ('oem_code', models.CharField(blank=True, default='', help_text='厂商名称缩写', max_length=50, null=True, verbose_name='厂商编码')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '型号-设备型号对照表',
                'verbose_name_plural': '型号-设备型号对照表',
            },
        ),
        migrations.CreateModel(
            name='D_P_I_C_V_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', max_length=50, verbose_name='设备型号')),
                ('dev_model_id', models.CharField(default='', max_length=50, verbose_name='设备型号id')),
                ('zdpi_sig_version', models.CharField(max_length=50, verbose_name='dpi配置文件版本')),
                ('zdpi_sig_file', models.FileField(upload_to='upload/dpiConfig/%Y/%m/%d', verbose_name='dpi配置文件')),
                ('user', models.CharField(max_length=30, verbose_name='操作人')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('md5', models.CharField(blank=True, max_length=50, null=True, verbose_name='MD5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-dpi配置文件版本',
                'verbose_name_plural': '版本-dpi配置文件版本',
            },
        ),
        migrations.CreateModel(
            name='S_C_V_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('superctl_version', models.CharField(help_text='superctl版本', max_length=50, verbose_name='superctl版本')),
                ('superctl_file', models.FileField(help_text='superctl文件', upload_to='upload/superctl/%Y/%m/%d', verbose_name='superctl文件')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('comment', models.TextField(blank=True, help_text='备注', max_length=500, null=True, verbose_name='备注')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-SuperCtl版本',
                'verbose_name_plural': '版本-SuperCtl版本',
            },
        ),
        migrations.CreateModel(
            name='S_D_C_F_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('superdcf_version', models.CharField(help_text='SuperDConfig版本', max_length=50, verbose_name='SuperDConfig版本')),
                ('superdcf_file', models.FileField(help_text='SuperDConfig文件', upload_to='upload/superdcf/%Y/%m/%d', verbose_name='SuperDConfig文件')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('type', models.CharField(blank=True, help_text='类型', max_length=50, null=True, verbose_name='类型')),
                ('comment', models.TextField(blank=True, help_text='备注', max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': 'SuperD 配置文件',
                'verbose_name_plural': 'SuperD 配置文件',
            },
        ),
        migrations.CreateModel(
            name='S_D_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('superd_version', models.CharField(help_text='superd版本', max_length=50, verbose_name='superd版本')),
                ('superd_file', models.FileField(help_text='superd文件', upload_to='upload/supertack/%Y/%m/%d', verbose_name='superd文件')),
                ('download_url', models.CharField(default='', help_text='下载url', max_length=200, verbose_name='下载url')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('build_reason', models.TextField(blank=True, help_text='构建说明', max_length=500, null=True, verbose_name='构建说明')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('build_result', models.CharField(blank=True, help_text='构建结果', max_length=50, null=True, verbose_name='构建结果')),
                ('build_status', models.CharField(blank=True, help_text='构建状态码', max_length=50, null=True, verbose_name='构建状态码')),
                ('build_type', models.CharField(blank=True, default='', help_text='构建类型', max_length=50, null=True, verbose_name='构建类型')),
                ('time_stamp', models.CharField(blank=True, default='0', help_text='时间戳', max_length=50, null=True, verbose_name='时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-SuperD版本',
                'verbose_name_plural': '版本-SuperD版本',
            },
        ),
        migrations.CreateModel(
            name='S_D_S_V_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rom_version', models.CharField(help_text='固件版本', max_length=100, verbose_name='固件版本')),
                ('docking_solution', models.CharField(choices=[('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0')], default='1.0', help_text='对接方案', max_length=32, verbose_name='对接方案')),
                ('pack_type', models.CharField(choices=[('gzip', 'gzip'), ('lzma', 'lzma')], help_text='压缩方式', max_length=30, verbose_name='压缩方式')),
                ('package_contains_path', models.CharField(default='sapi/run', help_text='压缩包内路径', max_length=100, verbose_name='压缩包内路径')),
                ('package_contains_path_type', models.CharField(default='supertack', help_text='压缩包内路径类型', max_length=100, verbose_name='压缩包内路径类型')),
                ('user', models.CharField(help_text='操作人', max_length=50, verbose_name='操作人')),
                ('comment', models.TextField(blank=True, help_text='备注', max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('dev_model', models.ForeignKey(default='', help_text='设备型号', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='strategy.D_M_DB', verbose_name='设备型号id')),
                ('superctl_version', models.ForeignKey(blank=True, help_text='连接器id', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.S_C_V_DB', verbose_name='连接器id')),
                ('superd_version', models.ForeignKey(blank=True, help_text='插件id', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.S_D_DB', verbose_name='插件id')),
                ('superdcf_version', models.ForeignKey(blank=True, help_text='配置文件id', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.S_D_C_F_DB', verbose_name='配置文件id')),
            ],
            options={
                'verbose_name': 'superD 策略版本信息',
                'verbose_name_plural': 'superD 策略版本信息',
            },
        ),
        migrations.CreateModel(
            name='S_T_V_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('supertack_version', models.CharField(help_text='supertack版本', max_length=50, verbose_name='supertack版本')),
                ('supertack_file', models.FileField(help_text='supertack文件', upload_to='upload/supertack/%Y/%m/%d', verbose_name='supertack文件')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('comment', models.TextField(blank=True, help_text='备注', max_length=500, null=True, verbose_name='备注')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-SuperTack版本',
                'verbose_name_plural': '版本-SuperTack版本',
            },
        ),
        migrations.AddField(
            model_name='s_d_s_v_db',
            name='supertack_version',
            field=models.ForeignKey(blank=True, help_text='连接器(C)id', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.S_T_V_DB', verbose_name='连接器(C)id'),
        ),
        migrations.AddField(
            model_name='s_d_s_v_db',
            name='zdpi_sig_version',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.D_P_I_C_V_DB', verbose_name='dpi配置文件id'),
        ),
    ]
