# Generated by Django 2.0.2 on 2019-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='O_E_M_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_name', models.CharField(blank=True, max_length=100, verbose_name='生产厂商')),
                ('oem_code', models.CharField(blank=True, help_text='厂商名称缩写', max_length=50, verbose_name='厂商编码')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '厂商-厂商信息',
                'verbose_name_plural': '厂商-厂商信息',
            },
        ),
        migrations.RemoveField(
            model_name='s_d_s_v_db',
            name='superctl_version',
        ),
        migrations.AddField(
            model_name='s_t_v_db',
            name='supertack_type',
            field=models.CharField(default='c_sapiloader', help_text='supertack型号', max_length=50, verbose_name='supertack型号'),
        ),
        migrations.DeleteModel(
            name='S_C_V_DB',
        ),
    ]
