# Generated by Django 2.0.2 on 2019-07-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20190628_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_A_L_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('sapiloaderC_version', models.CharField(help_text='sapiloader版本', max_length=50, verbose_name='sapiloader版本')),
                ('sapiloaderC_file', models.FileField(help_text='sapiloader文件', upload_to='upload/supertack/%Y/%m/%d', verbose_name='sapiloader文件')),
                ('sapiloader_type', models.CharField(default='c_sapiloader', help_text='sapiloader型号', max_length=50, verbose_name='sapiloader型号')),
                ('download_url', models.CharField(default='', help_text='下载url', max_length=200, verbose_name='下载url')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('build_reason', models.TextField(blank=True, help_text='构建说明', max_length=500, null=True, verbose_name='构建说明')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('build_result', models.CharField(blank=True, help_text='构建结果', max_length=50, null=True, verbose_name='构建结果')),
                ('build_status', models.CharField(blank=True, help_text='构建状态码', max_length=50, null=True, verbose_name='构建状态码')),
                ('build_type', models.CharField(blank=True, default='', help_text='构建类型', max_length=50, null=True, verbose_name='构建类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-加载器版本(C)',
                'verbose_name_plural': '版本-加载器版本(C)',
            },
        ),
    ]
