# Generated by Django 2.0.2 on 2019-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_s_a_l_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_T_L_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('user', models.CharField(default='', max_length=50, verbose_name='操作人')),
                ('build_reason', models.TextField(default='', max_length=200, verbose_name='构建原因')),
                ('build_tag', models.TextField(default='', max_length=200, verbose_name='构建版本')),
                ('build_result', models.TextField(default='', max_length=1000, verbose_name='构建结果')),
                ('build_status', models.TextField(default='', max_length=200, verbose_name='构建状态码')),
                ('type', models.CharField(default='', max_length=30, verbose_name='构建类型')),
                ('comment', models.CharField(default='', max_length=200, verbose_name='备注')),
                ('time_stamp', models.CharField(blank=True, default='0', help_text='时间戳', max_length=50, null=True, verbose_name='时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '插件-构建日志',
                'verbose_name_plural': '插件-构建日志',
            },
        ),
        migrations.CreateModel(
            name='M_D_M_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('原始名称', '原始名称'), ('大小写不同', '大小写不同'), ('交叉编译链简称', '交叉编译链简称'), ('型号不一样', '型号不一样'), ('交叉编译链一样', '交叉编译链一样')], default='原始名称', help_text='类型', max_length=50, verbose_name='类型')),
                ('dev_model', models.CharField(blank=True, help_text='类型', max_length=50, verbose_name='设备型号')),
                ('map_dev_model', models.CharField(blank=True, max_length=50, verbose_name='Cbuild中设备型号')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '构建-设备型号构建映射表',
                'verbose_name_plural': '构建-设备型号构建映射表',
            },
        ),
        migrations.CreateModel(
            name='R_P_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('proxy_version', models.CharField(max_length=50, verbose_name='版本')),
                ('proxy_file', models.FileField(upload_to='upload/supertack/%Y/%m/%d', verbose_name='文件路径')),
                ('download_url', models.CharField(default='', help_text='下载url', max_length=200, verbose_name='下载url')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('build_reason', models.TextField(blank=True, help_text='构建说明', max_length=500, null=True, verbose_name='构建说明')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('build_result', models.CharField(blank=True, help_text='构建结果', max_length=50, null=True, verbose_name='构建结果')),
                ('build_status', models.CharField(blank=True, help_text='构建状态码', max_length=50, null=True, verbose_name='构建状态码')),
                ('build_type', models.CharField(blank=True, default='', help_text='构建类型', max_length=50, null=True, verbose_name='构建类型')),
                ('time_stamp', models.CharField(blank=True, default='0', help_text='时间戳', max_length=50, null=True, verbose_name='时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-反向代理版本',
                'verbose_name_plural': '版本-反向代理版本',
            },
        ),
        migrations.CreateModel(
            name='S_O_T_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=50, verbose_name='项目名称')),
                ('project_path', models.CharField(default='', max_length=100, verbose_name='项目路径')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='tag号')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='comment')),
                ('status', models.CharField(blank=True, default=1, max_length=50, verbose_name='状态')),
                ('user', models.CharField(max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-版本号信息记录',
                'verbose_name_plural': '版本-版本号信息记录',
            },
        ),
    ]
