# Generated by Django 2.0.2 on 2019-07-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_b_t_l_db_m_d_m_db_r_p_db_s_o_t_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_t_v_db',
            name='supertack_type',
        ),
    ]
