# Generated by Django 2.0.2 on 2019-07-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_remove_s_t_v_db_supertack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_t_v_db',
            name='supertack_type',
            field=models.CharField(default='c_sapiloader', help_text='supertack型号', max_length=50, verbose_name='supertack型号'),
        ),
    ]
