# Generated by Django 2.0.2 on 2019-07-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_s_t_v_db_supertack_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b_t_l_db',
            old_name='type',
            new_name='types',
        ),
    ]
