# Generated by Django 2.0.2 on 2019-07-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_auto_20190705_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b_t_l_db',
            old_name='types',
            new_name='type',
        ),
    ]
