# Generated by Django 2.0.2 on 2019-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0008_auto_20190705_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_d_s_v_db',
            name='zdpi_sig_version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='dpi配置文件id'),
        ),
    ]
