# Generated by Django 2.0.2 on 2019-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_b_p_r_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_O_P_L_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(max_length=50, verbose_name='设备型号')),
                ('rtype', models.CharField(blank=True, default='pg', max_length=50, verbose_name='上线类型')),
                ('user', models.CharField(max_length=50, verbose_name='操作人')),
                ('plug_title_name', models.CharField(default='', max_length=100, verbose_name='配置项名称')),
                ('plug_name', models.CharField(max_length=100, verbose_name='插件文件名称')),
                ('plug_md5', models.CharField(max_length=100, verbose_name='插件的md5值')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='上线版本号')),
                ('cmd_content', models.CharField(blank=True, default='', max_length=500, verbose_name='加载器执行命令')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='上线说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '插件-发布上线操作日志',
                'verbose_name_plural': '插件-发布上线操作日志',
            },
        ),
    ]
