# Generated by Django 2.0.2 on 2019-07-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0011_r_o_p_l_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_A_L_P_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='设备型号')),
                ('version', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='加载器版本')),
                ('reason', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='构建原因')),
                ('pack_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='包名称')),
                ('pack_save_path', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='包存放路径')),
                ('url', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='下载链接')),
                ('md5', models.CharField(default='', help_text='压缩包md5', max_length=100, verbose_name='压缩包md5')),
                ('user', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='构建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '打包结果-加载器包',
                'verbose_name_plural': '打包结果-加载器包',
            },
        ),
    ]
