# Generated by Django 2.0.2 on 2019-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0012_s_a_l_p_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_a_l_p_db',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='构建原因'),
        ),
    ]
