# Generated by Django 2.0.2 on 2019-07-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0013_auto_20190712_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D_P_I_C_V_DB',
        ),
        migrations.RemoveField(
            model_name='s_d_s_v_db',
            name='dev_model',
        ),
        migrations.RemoveField(
            model_name='s_d_s_v_db',
            name='superd_version',
        ),
        migrations.RemoveField(
            model_name='s_d_s_v_db',
            name='superdcf_version',
        ),
        migrations.RemoveField(
            model_name='s_d_s_v_db',
            name='supertack_version',
        ),
        migrations.AlterModelOptions(
            name='b_p_r_db',
            options={'verbose_name': '2.7-打包结果-PG包', 'verbose_name_plural': '2.7-打包结果-PG包'},
        ),
        migrations.AlterModelOptions(
            name='b_t_l_db',
            options={'verbose_name': '2.7-构建日志', 'verbose_name_plural': '2.7-构建日志'},
        ),
        migrations.AlterModelOptions(
            name='d_m_db',
            options={'verbose_name': '2.7-设备型号对照表', 'verbose_name_plural': '2.7-设备型号对照表'},
        ),
        migrations.AlterModelOptions(
            name='m_d_m_db',
            options={'verbose_name': '2.7-设备型号构建映射表', 'verbose_name_plural': '2.7-设备型号构建映射表'},
        ),
        migrations.AlterModelOptions(
            name='o_e_m_db',
            options={'verbose_name': '2.7-厂商信息', 'verbose_name_plural': '2.7-厂商信息'},
        ),
        migrations.AlterModelOptions(
            name='r_o_p_l_db',
            options={'verbose_name': '2.7-发布上线操作日志', 'verbose_name_plural': '2.7-发布上线操作日志'},
        ),
        migrations.AlterModelOptions(
            name='r_p_db',
            options={'verbose_name': '2.7-反向代理版本', 'verbose_name_plural': '2.7-反向代理版本'},
        ),
        migrations.AlterModelOptions(
            name='s_a_l_db',
            options={'verbose_name': '2.7-加载器版本(C)', 'verbose_name_plural': '2.7-加载器版本(C)'},
        ),
        migrations.AlterModelOptions(
            name='s_a_l_p_db',
            options={'verbose_name': '2.7-打包结果-加载器包', 'verbose_name_plural': '2.7-打包结果-加载器包'},
        ),
        migrations.AlterModelOptions(
            name='s_d_c_f_db',
            options={'verbose_name': '2.7-SuperD 配置文件', 'verbose_name_plural': '2.7-SuperD 配置文件'},
        ),
        migrations.AlterModelOptions(
            name='s_d_db',
            options={'verbose_name': '2.7-SuperD版本', 'verbose_name_plural': '2.7-SuperD版本'},
        ),
        migrations.AlterModelOptions(
            name='s_o_t_db',
            options={'verbose_name': '2.7-版本号信息记录', 'verbose_name_plural': '2.7-版本号信息记录'},
        ),
        migrations.AlterModelOptions(
            name='s_t_v_db',
            options={'verbose_name': '2.7-连接器版本', 'verbose_name_plural': '2.7-连接器版本'},
        ),
        migrations.DeleteModel(
            name='S_D_S_V_DB',
        ),
    ]
