# Generated by Django 2.0.2 on 2019-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0014_auto_20190716_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackDefaultConfigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(blank=True, default='fitall', max_length=50, null=True, verbose_name='设备型号')),
                ('pack_type', models.CharField(default='c_sapiloader', help_text='适配器版本', max_length=50, verbose_name='适配器版本')),
                ('compress_mode', models.CharField(choices=[('gzip', 'gzip'), ('lzma', 'lzma')], help_text='压缩方式', max_length=30, verbose_name='压缩方式')),
                ('docking_solution', models.CharField(choices=[('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0')], default='2.5', help_text='对接方案', max_length=32, verbose_name='对接方案')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('user', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='构建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
    ]
