# Generated by Django 2.0.2 on 2019-08-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0015_packdefaultconfigure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packdefaultconfigure',
            options={'verbose_name': '2.7-默认打包配置', 'verbose_name_plural': '2.7-默认打包配置'},
        ),
        migrations.AlterField(
            model_name='s_o_t_db',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='comment'),
        ),
    ]
