# Generated by Django 2.0.2 on 2019-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneapplicationsuser',
            name='status',
            field=models.CharField(blank=True, help_text='状态 0-删除, 1-存在', max_length=1, null=True, verbose_name='状态'),
        ),
    ]
