# Generated by Django 2.0.2 on 2019-08-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataplatform', '0002_phoneapplicationsuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneapplicationsuser',
            name='applicationsName',
            field=models.CharField(blank=True, help_text='应用名称', max_length=10, null=True, verbose_name='应用名称'),
        ),
    ]
