# Generated by Django 2.0.2 on 2019-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataplatform', '0003_auto_20190827_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, help_text='手机号码', max_length=11, null=True, verbose_name='手机号码')),
                ('phoneType', models.CharField(blank=True, choices=[('中国移动', '中国移动'), ('中国电信', '中国电信'), ('中国联通', '中国联通')], help_text='号码运营商', max_length=10, null=True, verbose_name='号码运营商')),
                ('utilizeUser', models.CharField(blank=True, help_text='使用人', max_length=10, null=True, verbose_name='使用人')),
                ('status', models.CharField(blank=True, help_text='状态 0-删除, 1-存在', max_length=1, null=True, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('user', models.CharField(blank=True, help_text='操作人', max_length=20, null=True, verbose_name='操作人')),
            ],
        ),
    ]
