# Generated by Django 2.0.2 on 2019-09-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataplatform', '0004_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneapplicationsuser',
            name='applicationsPass',
            field=models.CharField(blank=True, help_text='账户密码', max_length=50, null=True, verbose_name='账号密码'),
        ),
        migrations.AlterField(
            model_name='phoneapplicationsuser',
            name='status',
            field=models.CharField(blank=True, default=1, help_text='状态 0-删除, 1-存在', max_length=1, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.CharField(blank=True, default=1, help_text='状态 0-删除, 1-存在', max_length=1, null=True, verbose_name='状态'),
        ),
    ]
