# Generated by Django 2.0.2 on 2019-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='标题')),
                ('user', models.CharField(default='', max_length=50, verbose_name='操作人')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='内容')),
                ('type', models.CharField(blank=True, default='', max_length=30, verbose_name='类型')),
                ('location', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='位置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '公告-全局广播内容',
                'verbose_name_plural': '公告-全局广播内容',
            },
        ),
        migrations.CreateModel(
            name='dev_model_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('面板AP', '面板AP'), ('二合一', '二合一'), ('三合一', '三合一'), ('四合一', '四合一'), ('吸顶AP', '吸顶AP'), ('AC网关', 'AC网关'), ('光猫AP', '光猫AP'), ('嗅探光猫', '嗅探光猫'), ('嗅探2合1', '嗅探2合1'), ('室外AP', '室外AP'), ('机顶盒', '机顶盒'), ('交换机', '交换机')], help_text='类型', max_length=50, verbose_name='类型')),
                ('oem_id', models.CharField(blank=True, help_text='设备厂商id', max_length=50, verbose_name='设备厂商id')),
                ('zy_model', models.CharField(blank=True, help_text='中建智云型号', max_length=100, unique=True, verbose_name='中建智云型号')),
                ('oem_model', models.CharField(blank=True, help_text='厂商型号', max_length=100, verbose_name='厂商型号')),
                ('old_model', models.CharField(blank=True, help_text='老型号', max_length=100, verbose_name='老型号')),
                ('oem_name', models.CharField(blank=True, default='', help_text='厂商名称', max_length=100, null=True, verbose_name='厂商名称')),
                ('oem_code', models.CharField(blank=True, default='', help_text='厂商名称缩写', max_length=50, null=True, verbose_name='厂商编码')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '型号-设备型号对照表',
                'verbose_name_plural': '型号-设备型号对照表',
            },
        ),
        migrations.CreateModel(
            name='dpiConfigVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', max_length=50, verbose_name='设备型号')),
                ('dev_model_id', models.CharField(default='', max_length=50, verbose_name='设备型号id')),
                ('zdpi_sig_version', models.CharField(max_length=50, verbose_name='dpi配置文件版本')),
                ('zdpi_sig_file', models.FileField(upload_to='upload/dpiConfig/%Y/%m/%d', verbose_name='dpi配置文件')),
                ('user', models.CharField(max_length=30, verbose_name='操作人')),
                ('comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('md5', models.CharField(blank=True, max_length=50, null=True, verbose_name='MD5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-dpi配置文件版本',
                'verbose_name_plural': '版本-dpi配置文件版本',
            },
        ),
        migrations.CreateModel(
            name='map_dev_model_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('原始名称', '原始名称'), ('大小写不同', '大小写不同'), ('交叉编译链简称', '交叉编译链简称'), ('型号不一样', '型号不一样'), ('交叉编译链一样', '交叉编译链一样')], help_text='类型', max_length=50, verbose_name='类型')),
                ('dev_model', models.CharField(blank=True, help_text='类型', max_length=50, verbose_name='设备型号')),
                ('map_dev_model', models.CharField(blank=True, max_length=50, verbose_name='Cbuild中设备型号')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '构建-设备型号构建映射表',
                'verbose_name_plural': '构建-设备型号构建映射表',
            },
        ),
        migrations.CreateModel(
            name='oem_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_name', models.CharField(blank=True, max_length=100, verbose_name='生产厂商')),
                ('oem_code', models.CharField(blank=True, help_text='厂商名称缩写', max_length=50, verbose_name='厂商编码')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '厂商-厂商信息',
                'verbose_name_plural': '厂商-厂商信息',
            },
        ),
        migrations.CreateModel(
            name='Operatingtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=50, verbose_name='项目名称')),
                ('project_path', models.CharField(default='', max_length=100, verbose_name='项目路径')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='tag号')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='comment')),
                ('status', models.CharField(blank=True, default=1, max_length=50, verbose_name='状态')),
                ('user', models.CharField(max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-版本号信息记录',
                'verbose_name_plural': '版本-版本号信息记录',
            },
        ),
        migrations.CreateModel(
            name='sapiloader_pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='设备型号')),
                ('version', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='加载器版本')),
                ('reason', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='构建原因')),
                ('pack_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='包名称')),
                ('pack_save_path', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='包存放路径')),
                ('url', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='下载链接')),
                ('md5', models.CharField(default='', help_text='压缩包md5', max_length=100, verbose_name='压缩包md5')),
                ('user', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='构建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '打包结果-加载器包',
                'verbose_name_plural': '打包结果-加载器包',
            },
        ),
        migrations.CreateModel(
            name='sapiloaderCVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('sapiloaderC_version', models.CharField(help_text='sapiloaderC版本', max_length=50, verbose_name='sapiloaderC版本')),
                ('sapiloaderC_file', models.FileField(help_text='sapiloaderC文件', upload_to='upload/supertack/%Y/%m/%d', verbose_name='sapiloaderC文件')),
                ('download_url', models.CharField(default='', help_text='下载url', max_length=200, verbose_name='下载url')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('build_reason', models.TextField(blank=True, help_text='构建说明', max_length=500, null=True, verbose_name='构建说明')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('build_result', models.CharField(blank=True, help_text='构建结果', max_length=50, null=True, verbose_name='构建结果')),
                ('build_status', models.CharField(blank=True, help_text='构建状态码', max_length=50, null=True, verbose_name='构建状态码')),
                ('build_type', models.CharField(blank=True, default='', help_text='构建类型', max_length=50, null=True, verbose_name='构建类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-加载器版本(C)',
                'verbose_name_plural': '版本-加载器版本(C)',
            },
        ),
        migrations.CreateModel(
            name='superdVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('superd_version', models.CharField(help_text='superd版本', max_length=50, verbose_name='superd版本')),
                ('superd_file', models.FileField(help_text='superd文件', upload_to='upload/supertack/%Y/%m/%d', verbose_name='superd文件')),
                ('download_url', models.CharField(default='', help_text='下载url', max_length=200, verbose_name='下载url')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('build_reason', models.TextField(blank=True, help_text='构建说明', max_length=500, null=True, verbose_name='构建说明')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('build_result', models.CharField(blank=True, help_text='构建结果', max_length=50, null=True, verbose_name='构建结果')),
                ('build_status', models.CharField(blank=True, help_text='构建状态码', max_length=50, null=True, verbose_name='构建状态码')),
                ('build_type', models.CharField(blank=True, default='', help_text='构建类型', max_length=50, null=True, verbose_name='构建类型')),
                ('time_stamp', models.CharField(blank=True, default='0', help_text='时间戳', max_length=50, null=True, verbose_name='时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-superd版本',
                'verbose_name_plural': '版本-superd版本',
            },
        ),
        migrations.CreateModel(
            name='unpack_cmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='设备型号')),
                ('unpack_cmd', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='解压命令')),
                ('run_cmd', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='启动命令')),
                ('user', models.CharField(default='', max_length=50, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '记录-PG包解压命令',
                'verbose_name_plural': '记录-PG包解压命令',
            },
        ),
        migrations.RemoveField(
            model_name='dev_model',
            name='oem_id',
        ),
        migrations.AlterModelOptions(
            name='pack_list_contorl',
            options={'verbose_name': '打包结果-PG包', 'verbose_name_plural': '打包结果-PG包'},
        ),
        migrations.AlterModelOptions(
            name='version_contorl',
            options={'verbose_name': '版本-维护信息控制表', 'verbose_name_plural': '版本-维护信息控制表'},
        ),
        migrations.RemoveField(
            model_name='build_log',
            name='dev_model_id',
        ),
        migrations.RemoveField(
            model_name='pack_list_contorl',
            name='dev_model_id',
        ),
        migrations.RemoveField(
            model_name='version_contorl',
            name='superd_version',
        ),
        migrations.AddField(
            model_name='build_log',
            name='dev_model',
            field=models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='build_log',
            name='time_stamp',
            field=models.CharField(blank=True, default='0', help_text='时间戳', max_length=50, null=True, verbose_name='时间戳'),
        ),
        migrations.AddField(
            model_name='build_log',
            name='type',
            field=models.CharField(default='', max_length=30, verbose_name='构建类型'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='connector_version',
            field=models.CharField(default='1.0', help_text='连接器版本', max_length=32, verbose_name='连接器版本'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='dev_model',
            field=models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='md5',
            field=models.CharField(default='', help_text='压缩包md5', max_length=100, verbose_name='压缩包md5'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='pack_name',
            field=models.CharField(default='', help_text='压缩包名称', max_length=100, verbose_name='压缩包名称'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='package_contains_path',
            field=models.CharField(default='', help_text='包内路径', max_length=32, verbose_name='包内路径'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='package_contains_path_type',
            field=models.CharField(default='supertack', help_text='压缩包内路径类型', max_length=100, verbose_name='压缩包内路径类型'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='release_version',
            field=models.CharField(default='1.0', help_text='线上版本', max_length=32, verbose_name='线上版本'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='superdcf_version',
            field=models.CharField(default='1.0', help_text='配置文件版本', max_length=32, verbose_name='配置文件版本'),
        ),
        migrations.AddField(
            model_name='pack_list_contorl',
            name='zdpi_sig_version',
            field=models.CharField(default='1.0', max_length=32, verbose_name='DPI配置文件版本'),
        ),
        migrations.AddField(
            model_name='release_plug_log',
            name='cmd_content',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='加载器执行命令'),
        ),
        migrations.AddField(
            model_name='release_plug_log',
            name='plug_title_name',
            field=models.CharField(default='', max_length=100, verbose_name='配置项名称'),
        ),
        migrations.AddField(
            model_name='release_plug_log',
            name='rtype',
            field=models.CharField(blank=True, default='pg', max_length=50, verbose_name='上线类型'),
        ),
        migrations.AddField(
            model_name='superctlversion',
            name='dev_model',
            field=models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='superdcfversion',
            name='dev_model',
            field=models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='superdcfversion',
            name='type',
            field=models.CharField(blank=True, help_text='类型', max_length=50, null=True, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='supertackversion',
            name='dev_model',
            field=models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='version_contorl',
            name='package_contains_path',
            field=models.CharField(default='sapi/run', help_text='压缩包内路径', max_length=100, verbose_name='压缩包内路径'),
        ),
        migrations.AddField(
            model_name='version_contorl',
            name='package_contains_path_type',
            field=models.CharField(default='supertack', help_text='压缩包内路径类型', max_length=100, verbose_name='压缩包内路径类型'),
        ),
        migrations.AddField(
            model_name='version_contorl',
            name='sapiloaderC_version_id',
            field=models.CharField(blank=True, help_text='加载器(C)id', max_length=30, null=True, verbose_name='加载器(C)id'),
        ),
        migrations.AddField(
            model_name='version_contorl',
            name='superd_version_id',
            field=models.CharField(blank=True, help_text='插件id', max_length=30, null=True, verbose_name='插件id'),
        ),
        migrations.AddField(
            model_name='version_contorl',
            name='zdpi_sig_version_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='dpi配置文件id'),
        ),
        migrations.AlterField(
            model_name='pack_list_contorl',
            name='download_url',
            field=models.CharField(blank=True, help_text='下载地址', max_length=200, null=True, verbose_name='下载地址'),
        ),
        migrations.AlterField(
            model_name='pack_list_contorl',
            name='package',
            field=models.FileField(help_text='插件包', max_length=200, upload_to='upload/package/%Y/%m/%d', verbose_name='插件包'),
        ),
        migrations.AlterField(
            model_name='release_plug_log',
            name='plug_name',
            field=models.CharField(max_length=100, verbose_name='插件文件名称'),
        ),
        migrations.AlterField(
            model_name='sapiloaderversion',
            name='sapiloader_version',
            field=models.CharField(help_text='superloader版本', max_length=50, verbose_name='superloader版本'),
        ),
        migrations.AlterField(
            model_name='version_contorl',
            name='dev_model_id',
            field=models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号id'),
        ),
        migrations.AlterField(
            model_name='version_contorl',
            name='sapiloader_version_id',
            field=models.CharField(blank=True, help_text='加载器id', max_length=30, null=True, verbose_name='加载器id'),
        ),
        migrations.AlterField(
            model_name='version_contorl',
            name='superctl_version_id',
            field=models.CharField(blank=True, help_text='连接器id', max_length=30, null=True, verbose_name='连接器id'),
        ),
        migrations.AlterField(
            model_name='version_contorl',
            name='superdcf_version_id',
            field=models.CharField(blank=True, help_text='配置文件id', max_length=30, null=True, verbose_name='配置文件id'),
        ),
        migrations.AlterField(
            model_name='version_contorl',
            name='supertack_version_id',
            field=models.CharField(blank=True, help_text='连接器(C)id', max_length=30, null=True, verbose_name='连接器(C)id'),
        ),
        migrations.DeleteModel(
            name='dev_model',
        ),
        migrations.DeleteModel(
            name='oem',
        ),
    ]
