# Generated by Django 2.0.2 on 2019-03-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proxyVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_model', models.CharField(default='', help_text='设备型号', max_length=50, verbose_name='设备型号')),
                ('proxy_version', models.CharField(max_length=50, verbose_name='版本')),
                ('proxy_file', models.FileField(upload_to='upload/supertack/%Y/%m/%d', verbose_name='文件路径')),
                ('download_url', models.CharField(default='', help_text='下载url', max_length=200, verbose_name='下载url')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('build_reason', models.TextField(blank=True, help_text='构建说明', max_length=500, null=True, verbose_name='构建说明')),
                ('md5', models.CharField(blank=True, help_text='md5', max_length=50, null=True, verbose_name='MD5')),
                ('build_result', models.CharField(blank=True, help_text='构建结果', max_length=50, null=True, verbose_name='构建结果')),
                ('build_status', models.CharField(blank=True, help_text='构建状态码', max_length=50, null=True, verbose_name='构建状态码')),
                ('build_type', models.CharField(blank=True, default='', help_text='构建类型', max_length=50, null=True, verbose_name='构建类型')),
                ('time_stamp', models.CharField(blank=True, default='0', help_text='时间戳', max_length=50, null=True, verbose_name='时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '版本-反向代理版本',
                'verbose_name_plural': '版本-反向代理版本',
            },
        ),
    ]
