# Generated by Django 2.0.2 on 2019-04-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60, unique=True, verbose_name='信息名称')),
                ('content', models.CharField(max_length=100, verbose_name='信息内容')),
                ('remark', models.TextField(max_length=200, verbose_name='备注')),
                ('operator', models.CharField(help_text='操作人', max_length=80, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '基础配置表',
                'verbose_name_plural': '基础配置表',
            },
        ),
        migrations.CreateModel(
            name='CaseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=30, verbose_name='集合名称')),
                ('case_action', models.CharField(max_length=300, verbose_name='用例项')),
                ('status', models.CharField(default=1, max_length=2, verbose_name='有效性:1有效')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试集',
                'verbose_name_plural': '测试集',
            },
        ),
        migrations.CreateModel(
            name='DeviceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备厂商名称')),
                ('dev_sn', models.CharField(max_length=32, verbose_name='设备SN')),
                ('dev_model', models.CharField(max_length=20, verbose_name='智云型号')),
                ('dev_ip', models.CharField(max_length=15, verbose_name='设备IP')),
                ('dev_port', models.CharField(default='', max_length=10, verbose_name='访问端口')),
                ('dev_user', models.CharField(max_length=18, verbose_name='设备账户')),
                ('dev_password', models.CharField(max_length=20, verbose_name='设备密码')),
                ('status', models.CharField(choices=[('0', '空闲'), ('1', '预执行'), ('2', '执行中'), ('3', '失败')], default='0', max_length=2, verbose_name='状态')),
                ('operator', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('remark', models.TextField(max_length=200, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '设备状态表',
                'verbose_name_plural': '设备状态表',
            },
        ),
        migrations.CreateModel(
            name='ExecuteStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.CharField(max_length=30, verbose_name='测试集ID')),
                ('task_status', models.CharField(choices=[('0', '空闲'), ('1', '执行'), ('2', '执行中'), ('3', '失败')], default='0', max_length=6, verbose_name='任务状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('status', models.CharField(default=1, max_length=2, verbose_name='有效性:1有效')),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.DeviceDB', verbose_name='设备ID')),
            ],
            options={
                'verbose_name': '执行策略',
                'verbose_name_plural': '执行策略',
            },
        ),
        migrations.CreateModel(
            name='InitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='', max_length=100, verbose_name='操作指令')),
                ('initData', models.TextField(max_length=300, verbose_name='原始数据')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '原始数据',
                'verbose_name_plural': '原始数据',
            },
        ),
        migrations.CreateModel(
            name='StrategyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=30, verbose_name='操作指令')),
                ('check_rule', models.CharField(blank=True, max_length=100, verbose_name='校验参数')),
                ('check_data', models.CharField(blank=True, max_length=100, verbose_name='校验数据')),
                ('data', models.TextField(max_length=300, verbose_name='数据')),
                ('result', models.CharField(max_length=20, verbose_name='结论')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.DeviceDB', verbose_name='设备ID')),
            ],
            options={
                'verbose_name': '执行策略返回数据表',
                'verbose_name_plural': '执行策略返回数据表',
            },
        ),
        migrations.CreateModel(
            name='StrategyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.CharField(max_length=30, verbose_name='测试集ID')),
                ('task_status', models.CharField(choices=[('0', '创建'), ('1', '上传'), ('2', '成功'), ('3', '失败')], default='0', max_length=6, verbose_name='任务状态')),
                ('operator', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('strategyID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.ExecuteStrategy', verbose_name='策略ID')),
            ],
            options={
                'verbose_name': '执行策略记录表',
                'verbose_name_plural': '执行策略记录表',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args_command', models.CharField(max_length=50, verbose_name='操作指令')),
                ('args_name', models.CharField(max_length=30, verbose_name='匹配参数')),
                ('args_vales', models.CharField(blank=True, max_length=100, verbose_name='指定匹配内容')),
                ('args_remark', models.TextField(max_length=300, verbose_name='备注')),
                ('args_operator', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('status', models.CharField(default=1, max_length=2, verbose_name='有效性:1有效')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试用例配置',
                'verbose_name_plural': '测试用例配置',
            },
        ),
        migrations.AddField(
            model_name='strategydata',
            name='strategyRID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.StrategyRecord', verbose_name='记录表ID'),
        ),
        migrations.AddField(
            model_name='initdata',
            name='strategyRID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='checkout.StrategyRecord', verbose_name='记录表ID'),
        ),
    ]
