# Generated by Django 2.0.2 on 2019-04-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_strategyrecord_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseset',
            name='operator',
            field=models.CharField(default='', help_text='操作人', max_length=30, verbose_name='操作人'),
        ),
    ]
