# Generated by Django 2.0.2 on 2019-08-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('面板AP', '面板AP'), ('二合一', '二合一'), ('三合一', '三合一'), ('四合一', '四合一'), ('吸顶AP', '吸顶AP'), ('AC网关', 'AC网关'), ('光猫AP', '光猫AP'), ('嗅探光猫', '嗅探光猫'), ('嗅探2合1', '嗅探2合1'), ('室外AP', '室外AP'), ('机顶盒', '机顶盒'), ('交换机', '交换机')], help_text='类型', max_length=50, verbose_name='类型')),
                ('oem_id', models.CharField(blank=True, help_text='设备厂商id', max_length=50, verbose_name='设备厂商id')),
                ('zy_model', models.CharField(blank=True, help_text='中建智云型号', max_length=100, unique=True, verbose_name='中建智云型号')),
                ('oem_model', models.CharField(blank=True, help_text='厂商型号', max_length=100, verbose_name='厂商型号')),
                ('old_model', models.CharField(blank=True, help_text='老型号', max_length=100, verbose_name='老型号')),
                ('oem_name', models.CharField(blank=True, default='', help_text='厂商名称', max_length=100, null=True, verbose_name='厂商名称')),
                ('oem_code', models.CharField(blank=True, default='', help_text='厂商名称缩写', max_length=50, null=True, verbose_name='厂商编码')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '型号-设备型号对照表',
                'verbose_name_plural': '型号-设备型号对照表',
            },
        ),
        migrations.CreateModel(
            name='Oem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_name', models.CharField(blank=True, max_length=100, verbose_name='生产厂商')),
                ('oem_code', models.CharField(blank=True, help_text='厂商名称缩写', max_length=50, verbose_name='厂商编码')),
                ('comment', models.CharField(blank=True, default=None, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('user', models.CharField(help_text='操作人', max_length=30, verbose_name='操作人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '厂商-厂商信息',
                'verbose_name_plural': '厂商-厂商信息',
            },
        ),
    ]
